apiVersion: v1
kind: Service
metadata:
  name: client-worker-service
  namespace: development
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: client-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-worker
  namespace: development
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: client-worker
  template:
    metadata:
      labels:
        app: client-worker
    spec:
      nodeSelector:
        dedicated: deamond
      containers:
        - name: client-worker
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: redis-host
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: redis-password
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: kafka-host
            - name: LOGSTASH_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: logstash-host
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          allowedHostPaths:
            - pathPrefix: "/tmp/healthy"
              readOnly: false
          ports:
            - containerPort: 8000
          args:
            - /bin/sh
            - -c
            - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 1
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 1
            initialDelaySeconds: 30
